spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:products_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

logging:
  level:
    root: WARN
    com.inventory.product: INFO
